### ISSUE TITLE
Accessing chart instance

### ISSUE THREAD

**Issue by ayozebarrera** [gor181/react-chartjs-2#3]
Hi

I tried to access to the chart_instance of ChartComponent but I couldn't... I tried to pass a ref to my component but they are stateless... any advice?

**Comment by gor181** [comment]
Hey @ayozebarrera,

Looking into it, thanks for contributions

**Comment by ayozebarrera** [comment]
Great, I tried to give a ref to the chart but they are stateless components and they doesn't accept ref prop.

Just changing components to have state, I could ref them and access chart_instance like this:

```js
...
<Bar ref="myChart" .... />
....
```
```js
let chart = this.refs.myChart.chart_instance;
chart.update();
//and whatever we need ;)
```

If I'm wrong on anything tell me to know

**Comment by gor181** [comment]
Hey @ayozebarrera , 

do you have time for PR? Otherwise I may fix it by EOD or tomorrow morning./

**Comment by gor181** [comment]
Apologies for delaying this fix, was a pretty though week. On it.

**Comment by ayozebarrera** [comment]
@gor181 never saw your previous comment. I could try but maybe thursday or friday!

**Comment by rycastaneda** [comment]
is this now possible?

**Comment by gor181** [comment]
Hey @ayozebarrera @rycastaneda,

It should work now.

Apologies for the delay.

Cheerio,
Goran

**Comment by ayozebarrera** [comment]
Dont worry @gor181 

I just updated the npm package and I still have the same problem, components are stateless... I guess is a version issue or something

**Comment by yairEO** [comment]
Does this still work with the changes made to `ref` in recent React?

**Comment by guifeliper** [comment]
It is working for me guys.  
I am new to React, so I don't if I should use the createRef in that case, let me know if anyone has a better method. 

My code is like that:

```
...
 const myChartRef = React.createRef();
  const handleResetZoom = () => {
    let chart = myChartRef.current.chartInstance;
    chart.resetZoom();
  };
...
```

```
...
     <div className={classes.chartContainer}>
          <Line
            ref={myChartRef}
            data={chartData}
            options={options}
          />
        </div>
...
```
