### ISSUE TITLE
Defaults creating error

### ISSUE THREAD

**Issue by nealoke** [gor181/react-chartjs-2#89]
I'm trying to use the { defaults } provided by your wrapper but when I pass these into a <Bar /> I get all kinds of errors. (I am not yet modifying these defaults)

**My Code**
```
import { Bar, defaults } from 'react-chartjs-2';

// component level
<Bar redraw data={this.props.chartData} height={300} options={defaults} />
```

**Error in console**

```
core.controller.js:443 Uncaught TypeError: Cannot set property '_data' of undefined
    at Chart.Controller.update (core.controller.js:443)
    at Chart.Controller.resize (core.controller.js:306)
    at eval (core.controller.js:224)
    at eval (core.helpers.js:982)
update @ core.controller.js:443
resize @ core.controller.js:306
(anonymous) @ core.controller.js:224
(anonymous) @ core.helpers.js:982
scale.radialLinear.js:113 Uncaught (in promise) TypeError: Cannot read property 'callback' of undefined
    at ChartElement.convertTicksToLabels (scale.radialLinear.js:113)
    at ChartElement.update (core.scale.js:94)
    at getMinimumBoxSize (core.layoutService.js:144)
    at Object.helpers.each (core.helpers.js:23)
    at Object.update (core.layoutService.js:155)
    at Chart.Controller.updateLayout (core.controller.js:381)
    at Chart.Controller.initialize (core.controller.js:250)
    at new Chart.Controller (core.controller.js:231)
    at new Chart (core.js:7)
    at ChartComponent.renderChart (index.js:212)
```

**Version**
_Chartjs:_ v2.4.0

**Comment by jerairrest** [comment]
Does using the `release-2.0.0` fix this issue by any chance?

**Comment by nealoke** [comment]
@jerairrest Will check this asap, but what is the advantage of using the provided defaults? And where do you merge these with your preferences? Is this on the root of your react app for example?

**Comment by jerairrest** [comment]
Alrighty, after playing around a bit more it looks like you only need to use merge the global defaults along with the chart specific defaults to get the full set.

```
const {global, bar} = defaults;

		const options = {
			...global,
			...bar,
			responsive: true,
			title: {
				display: true,
				text: 'Custom Chart Title',
				fontSize: 150
			},
			scales: {
				xAxes: [{
					stacked: true
				}],
				yAxes: [{
					stacked: true
				}]
			}
		};
```

**Comment by jerairrest** [comment]
@nealoke I'm closing this for now. Let me know if you are still having troubles

**Comment by Harsha3878** [comment]
Recently i have updated the chart.js and react-chartjs-2 library to the latest version 3.0.0-beta. and i am trying this in my code.
import { Doughnut, Line } from 'react-chartjs-2';
toolDatacli: {
              labels: [
                  'SourceClear ',
                  'Hawkeye', 
                  'Sonarqube ',
                  ' Glair ',
                  'Coverity '
                
              ],
              datasets: [{
                  data: [
                    10,
                    20,
                    30,
                    40,
                    50
                    
                    ],
                  backgroundColor: [
                  '#36A2EB',
                  '#FFCE56',
                  '#FF851B',
                  '#7FDBFF',
                  '#FF0000'
                  ],
                  hoverBackgroundColor: [
                  '#36A2EB',
                  '#FFCE56',
                  '#FF851B',
                  '#7FDBFF',
                  '#FF0000'
                  ]
              }]
              },


<div class="column">
                <h5>CLI Tools Usage</h5>
                {toolDatacli && <Doughnut data={toolDatacli}  /> }
              </div>

when i start the application i am getting error like 
TypeError: Cannot read property 'defaults' of undefined
(anonymous function)
D:/GoLang/GoProject/src/git02.ae.sda.corp.telstra.com/pip/svc-dashboard-web/node_modules/react-chartjs-2/es/index.js:643
  640 | }(_react["default"].Component);
  641 | 
  642 | exports.Scatter = Scatter;
> 643 | var defaults = _chart["default"].defaults;
  644 | exports.defaults = defaults;
View compiled
./node_modules/react-chartjs-2/es/index.js
http://localhost:3000/static/js/0.chunk.js:30275:30
__webpack_require__
D:/GoLang/GoProject/src/git02.ae.sda.corp.telstra.com/pip/svc-dashboard-web/webpack/bootstrap:851
  848 | 
  849 | __webpack_require__.$Refresh$.init();
  850 | try {
> 851 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  852 | } finally {
  853 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  854 | }
![error](https://user-images.githubusercontent.com/32671287/94154231-50f76d00-fe9b-11ea-968b-6754da633e61.png)
![error](https://user-images.githubusercontent.com/32671287/94154252-581e7b00-fe9b-11ea-9033-e14350485401.png)

**Comment by robertjwozniak** [comment]
@Harsha3878 Did you find a solution to this problem? I'm having this issue as well

**Comment by robertjwozniak** [comment]
I'm actually having this issue:
`TypeError: _chart.default is undefined`

**Comment by isailaoctavian** [comment]
@Harsha3878 I have exactly the same issue like you.. Did you find a solution?

**Comment by isailaoctavian** [comment]
@robertjwozniak  Please tag me if you find a solution

**Comment by insivika** [comment]
Same issue here

**Comment by douglasjauhar** [comment]
Fucking issue just noww

**Comment by douglasjauhar** [comment]
2 months ago I developed a project there were no issues at all, but now suddenly there are issues that are annoying, anyone who can help to provide information

**Comment by zeyker** [comment]
I was having the same issue, i fixed it going back to version "chart.js": "^2.9.4" and keeping "react-chartjs-2": "^2.11.1"

**Comment by himanshu76200** [comment]
> I was having the same issue, i fixed it going back to version "chart.js": "^2.9.4" and keeping "react-chartjs-2": "^2.11.1"
> @isailaoctavian

Yes I believe there is some problem with the latest version of chart.js.
BTW thanks a lot for ur Comment

**Comment by aaaaayushh** [comment]
> I'm actually having this issue:
> `TypeError: _chart.default is undefined`

same issue for me 
@zeyker tried installing the older version of chart.js but still the same problem

**Comment by orisailes** [comment]
got the same issue.
solve it by change the `"chart.js": "^2.9.4",` in your package.json
then delete node modules folder, then in terminal run `npm install` .

**Comment by levankhoabhc** [comment]
> got the same issue.
> solve it by change the `"chart.js": "^2.9.4",` in your package.json
> then delete node modules folder, then in terminal run `npm install` .

This works for me, thanks.

**Comment by insivika** [comment]
Also fixed it for me, thank you!

**Comment by ArianNexux** [comment]
> solve it by change the `"chart.js": "^2.9.4",` in your package.json

Solved me too

**Comment by isailaoctavian** [comment]
@orisailes tanks a lot, you save the day! God bless you

**Comment by devidb00** [comment]
Thank you very much for the help !

**Comment by AnwarHossainSR** [comment]
Thank you so much. the problem is solved for me

**Comment by gozel-cholukova** [comment]
> got the same issue.
> solve it by change the `"chart.js": "^2.9.4",` in your package.json
> then delete node modules folder, then in terminal run `npm install` .
Thanks a Lot... very helpful

**Comment by Kbllo** [comment]
Thanks

> 
> 
> > got the same issue.
> > solve it by change the `"chart.js": "^2.9.4",` in your package.json
> > then delete node modules folder, then in terminal run `npm install` .
> 
> This works for me, thanks.

**Comment by serhiy1017** [comment]
Hey, thanks a lot for your help

**Comment by po4tion** [comment]
Thanks!!
I solved this problem. Removed latest version "chart.js" and added chart.js@2.9.4

**Comment by savindug** [comment]
thanks

**Comment by Byte-Box** [comment]
> got the same issue.
> solve it by change the `"chart.js": "^2.9.4",` in your package.json
> then delete node modules folder, then in terminal run `npm install` .

This worked like a charm, thanks so much

**Comment by adedking** [comment]
> got the same issue.
> solve it by change the `"chart.js": "^2.9.4",` in your package.json
> then delete node modules folder, then in terminal run `npm install` .

Was having the same issue. This worked for me. Thanks a lot

**Comment by nimrod-cohen** [comment]
Why is this issue closed, its definitely not resolved, and all the people here saying "solved" when all they did was downgraded to previous version.
The issue remains since v.3.02 - please reopen this issue.

**Comment by arjun-myanger** [comment]
> got the same issue.
> solve it by change the `"chart.js": "^2.9.4",` in your package.json
> then delete node modules folder, then in terminal run `npm install` .

Thanks man!

**Comment by JavascriptDeNoobAPro** [comment]
Mee too ! I just downgraded chart.js to ^2.9.4, and it worked, - but the issue is not solved.
Please reopen this issue.
cheers!

**Comment by walidilyas** [comment]
solve it by change the "chart.js": "^2.9.4"

**Comment by developer-junaid** [comment]
> I was having the same issue, i fixed it going back to version "chart.js": "^2.9.4" and keeping "react-chartjs-2": "^2.11.1"
> @isailaoctavian

It worked, love you man !

**Comment by Tanvin-Ahmed** [comment]
I install "chart.js":"^2.9.4" but I get another error TypeError: Cannot create property 'datasets' on boolean 'true'. How can I fixed it?

**Comment by Tanvin-Ahmed** [comment]
I install "chart.js": "^2.9.4" but I get another error.  TypeError: Cannot create property 'datasets' on boolean 'true' . How can I fixed it?

![image](https://user-images.githubusercontent.com/71924916/115432924-bf7d8d00-a228-11eb-8a1b-b2cae28e3931.png)

**Comment by Yansb** [comment]
@orisailes Worked, thanks

**Comment by duttanaman1** [comment]
I am facing the same issue even with "chart.js": "^2.9.4", and "react-chartjs-2": "^2.11.1", Cannot read property 'defaults' of undefined

**Comment by SanjeevYadavcr7** [comment]
> got the same issue.
> solve it by change the `"chart.js": "^2.9.4",` in your package.json
> then delete node modules folder, then in terminal run `npm install` .

Thanks...It's working.

**Comment by YakovlevCoded** [comment]
Hi! We have updated the wrapper. Try to use the latest version ^3.0.2 with Chart.js ^3.x.

1st -> npm uninstall react-chartjs-2 chart.js
Then use this command definitely solve your problem

npm install --save react-chartjs-2 chart.js

**Comment by thierryler** [comment]
I do have the same issue with 
"chart.js": "2.9.4"
"react-chartjs-2": "2.11.1"
"@types/chart.js": "^2.9.32"

I can't go to chartjs 3 because I have to support IE11 :-(
